---
title: "Expectation Maximization for Gaussian Clustering"
output: html_notebook
---

```{r}
library(ggplot2)
library(mvtnorm)
library(plot3D)
```

```{r}
data <- as.matrix(read.csv(file = './data/kmeans.csv'))
```

```{r}
k <- 3

sample_size <- nrow(data)
no_of_dimensions <- ncol(data)

# Set initial parameters
set.seed(103)
mu <- matrix(sample(-10:10, no_of_dimensions * k, replace = TRUE), nrow = no_of_dimensions, ncol = k)
Sigma <- array(data = NaN, c(no_of_dimensions, no_of_dimensions, k))
for(i in seq(1:k)) {
  Sigma[, , i] <- cov(data)
}
```

<h3>Expectation Step</h3>

```{r}
E_step <- function(sample_data, mu, Sigma, k, cluster_sizes) {
  
  sample_size <- nrow(sample_data)
  
  Gaussian_likelihoods <- matrix(0, sample_size, k)
  
  for(i in seq(1:k)) {
    # Gaussian_likelihoods[, i] <- (1 / cluster_sizes[i]) * dmvnorm(sample_data, mu[, i], Sigma[, , i])
    Gaussian_likelihoods[, i] <- dmvnorm(sample_data, mu[, i], Sigma[, , i])
  }
  
  Gaussian_likelihoods <- Gaussian_likelihoods/ rowSums(Gaussian_likelihoods)
  
  return(Gaussian_likelihoods)
}
```

```{r}
# Testing E-step
cluster_sizes <- rep(nrow(data)/ k, k)
Gaussian_likelihoods <- E_step(data, mu, Sigma, k, cluster_sizes)
print(rowSums(Gaussian_likelihoods))
```

```{r}
print(colSums(Gaussian_likelihoods))
```

```{r}
dim(data)
```


```{r}
dim(Gaussian_likelihoods)
```

<h3>Maximization Step</h3>

```{r}
M_step <- function(sample_data, Gaussian_likelihoods, k, cluster_sizes) {
  sample_size <- nrow(sample_data)
  no_of_dimensions <- ncol(sample_data)
  next_mu <- matrix(NA, no_of_dimensions, k)
  next_Sigma <- array(data = NA, c(no_of_dimensions, no_of_dimensions, k))
  
  Gaussian_cluster <- array(data = NaN, c(sample_size, no_of_dimensions, k))
  for(i in seq(1:k)) {
    Gaussian_cluster[, , i] <- rep(Gaussian_likelihoods[, i], no_of_dimensions)
  }
  
  for(i in seq(1:k)) {
    
    # Gaussian_cluster[, , i] <- Gaussian_likelihoods[, i] * sample_data # Data estimated to belong to Gaussian number i
    
    next_mu[, i] <- colSums(Gaussian_likelihoods[, i] * sample_data)/ cluster_sizes[i]
    
    standard_deviations <- Gaussian_likelihoods[, i] * (sample_data - rep(t(next_mu[, i]), sample_size))
    # standard_deviations <-(Gaussian_likelihoods[, i] * sample_data - rep(t(next_mu[, i]), sample_size))
    next_Sigma[, , i] <- (t(standard_deviations) %*% standard_deviations) / cluster_sizes[i]
  }
  
  parameter_estimates <- list(next_mu, next_Sigma)
  names(parameter_estimates) <- c("Next_Mu", "Next_Sigma")
  
  estimates_and_clusters <- list(parameter_estimates, Gaussian_cluster)
  names(estimates_and_clusters) <- c("Parameter_Estimates", "Gaussian_Clusters")
  
  return(estimates_and_clusters)
}
```

```{r}
estimates_and_clusters <- M_step(data, Gaussian_likelihoods, k, colSums(Gaussian_likelihoods))
parameter_estimates <- estimates_and_clusters$Parameter_Estimates
print(parameter_estimates)
```

<h3>EM Loop</h3>

```{r}
Gaussian_Mixture_Model_Clustering <- function (sample_data, mu, Sigma, k, margin_of_error) {
  
  sample_size <- nrow(sample_data)
  cluster_sizes <- rep(sample_size/ k, k)
  
  prev_likelihoods <- matrix(data = 0, nrow = sample_size, ncol = k)
  convergence <- FALSE
  
  i <- 1
  while(!convergence) { # To be replaced with convergence check
    Gaussian_likelihoods <- E_step(sample_data, mu, Sigma, k, cluster_sizes)
    
    cluster_sizes <- colSums(Gaussian_likelihoods)
    estimates_and_clusters <- M_step(sample_data, Gaussian_likelihoods, k, cluster_sizes)
    
    parameter_estimates <- estimates_and_clusters$Parameter_Estimates
    
    mu <- parameter_estimates$Next_Mu
    Sigma <- parameter_estimates$Next_Sigma
    
    error <- Gaussian_likelihoods - prev_likelihoods
    # print(paste("error = ", summary(error)))
    acceptable_error <- margin_of_error * prev_likelihoods
    # print(paste("acceptable error = ", summary(acceptable_error)))
    
    if(all(error <= acceptable_error)) {
      convergence <- TRUE
    }
    
    prev_likelihoods <- Gaussian_likelihoods
    i <- i + 1
  }
  
  result_summary <- list(i, parameter_estimates, estimates_and_clusters$Gaussian_Clusters)
  names(result_summary) <- c("No_of_Iterations", "Parameter_Estimates", "Gaussian_Clusters")
  
  return(result_summary)
}
```

```{r}
result_summary <- Gaussian_Mixture_Model_Clustering(data, mu, Sigma, k, margin_of_error = 0.0000000000001)
no_of_interations <- result_summary$No_of_Iterations
parameter_estimates <- result_summary$Parameter_Estimates
print(paste("Reached convergence at iteration ", no_of_interations, " ... "))
print("Parameter Estimates")
print(parameter_estimates) # Output = $Next_Mu (each column is vector of means for a Gaussian); $Next_Sigma (2D slices printed are the Variance-Covariance Matrices of the Gaussians)
```
